language: node_js
node_js:
  - "6.3.0"
#  - "iojs"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
    - npm install && yarn install

script:
    - yarn test