language: node_js
node_js:
#  - "8.10.0"
  - "10"
  - "12"
#  - "iojs"

before_install:
#  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.5
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
    - npm install && yarn install

script:
    - yarn test